config/routes.rb
Rails.application.routes.draw do
  resources :read_data
  resources :periods
  resources :buy_and_keeps
  resources :rentals
  resources :sky_stores
  resources :calls
  resources :call_charges
  resources :subscriptions
  resources :packages
  resources :statements
  resources :bills

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/models/buy_and_keep.rb
class BuyAndKeep < ActiveRecord::Base
end

app/models/call.rb
class Call < ActiveRecord::Base
end

app/models/call_charge.rb
class CallCharge < ActiveRecord::Base
end

app/models/package.rb
class Package < ActiveRecord::Base
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/read_datum.rb
class ReadDatum < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/models/sky_store.rb
class SkyStore < ActiveRecord::Base
end

app/models/statement.rb
class Statement < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/buy_and_keeps_controller.rb
class BuyAndKeepsController < ApplicationController
  before_action :set_buy_and_keep, only: [:show, :edit, :update, :destroy]

  # GET /buy_and_keeps
  # GET /buy_and_keeps.json
  def index
    @buy_and_keeps = BuyAndKeep.all
  end

  # GET /buy_and_keeps/1
  # GET /buy_and_keeps/1.json
  def show
  end

  # GET /buy_and_keeps/new
  def new
    @buy_and_keep = BuyAndKeep.new
  end

  # GET /buy_and_keeps/1/edit
  def edit
  end

  # POST /buy_and_keeps
  # POST /buy_and_keeps.json
  def create
    @buy_and_keep = BuyAndKeep.new(buy_and_keep_params)

    respond_to do |format|
      if @buy_and_keep.save
        format.html { redirect_to @buy_and_keep, notice: 'Buy and keep was successfully created.' }
        format.json { render :show, status: :created, location: @buy_and_keep }
      else
        format.html { render :new }
        format.json { render json: @buy_and_keep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buy_and_keeps/1
  # PATCH/PUT /buy_and_keeps/1.json
  def update
    respond_to do |format|
      if @buy_and_keep.update(buy_and_keep_params)
        format.html { redirect_to @buy_and_keep, notice: 'Buy and keep was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy_and_keep }
      else
        format.html { render :edit }
        format.json { render json: @buy_and_keep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buy_and_keeps/1
  # DELETE /buy_and_keeps/1.json
  def destroy
    @buy_and_keep.destroy
    respond_to do |format|
      format.html { redirect_to buy_and_keeps_url, notice: 'Buy and keep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy_and_keep
      @buy_and_keep = BuyAndKeep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_and_keep_params
      params.require(:buy_and_keep).permit(:title, :cost, :skyStore_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/buy_and_keeps_helper.rb
module BuyAndKeepsHelper
end

app/helpers/call_charges_helper.rb
module CallChargesHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/read_data_helper.rb
module ReadDataHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/sky_stores_helper.rb
module SkyStoresHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/buy_and_keeps/_form.html.erb
<%= form_for(@buy_and_keep) do |f| %>
  <% if @buy_and_keep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buy_and_keep.errors.count, "error") %> prohibited this buy_and_keep from being saved:</h2>

      <ul>
      <% @buy_and_keep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :skyStore_id %><br>
    <%= f.number_field :skyStore_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buy_and_keeps/edit.html.erb
<h1>Editing Buy And Keep</h1>

<%= render 'form' %>

<%= link_to 'Show', @buy_and_keep %> |
<%= link_to 'Back', buy_and_keeps_path %>

app/views/buy_and_keeps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buy And Keeps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cost</th>
      <th>Skystore</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buy_and_keeps.each do |buy_and_keep| %>
      <tr>
        <td><%= buy_and_keep.title %></td>
        <td><%= buy_and_keep.cost %></td>
        <td><%= buy_and_keep.skyStore_id %></td>
        <td><%= link_to 'Show', buy_and_keep %></td>
        <td><%= link_to 'Edit', edit_buy_and_keep_path(buy_and_keep) %></td>
        <td><%= link_to 'Destroy', buy_and_keep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy and keep', new_buy_and_keep_path %>

app/views/buy_and_keeps/new.html.erb
<h1>New Buy And Keep</h1>

<%= render 'form' %>

<%= link_to 'Back', buy_and_keeps_path %>

app/views/buy_and_keeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @buy_and_keep.title %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @buy_and_keep.cost %>
</p>

<p>
  <strong>Skystore:</strong>
  <%= @buy_and_keep.skyStore_id %>
</p>

<%= link_to 'Edit', edit_buy_and_keep_path(@buy_and_keep) %> |
<%= link_to 'Back', buy_and_keeps_path %>