config/routes.rb
Rails.application.routes.draw do
  resources :read_data
  resources :periods
  resources :buy_and_keeps
  resources :rentals
  resources :sky_stores
  resources :calls
  resources :call_charges
  resources :subscriptions
  resources :packages
  resources :statements
  resources :bills

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/models/buy_and_keep.rb
class BuyAndKeep < ActiveRecord::Base
end

app/models/call.rb
class Call < ActiveRecord::Base
end

app/models/call_charge.rb
class CallCharge < ActiveRecord::Base
end

app/models/package.rb
class Package < ActiveRecord::Base
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/read_datum.rb
class ReadDatum < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/models/sky_store.rb
class SkyStore < ActiveRecord::Base
end

app/models/statement.rb
class Statement < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  require 'json'
  require 'open-uri'

  # GET /bills
  # GET /bills.json
  def index
    source = "http://safe-plains-5453.herokuapp.com/bill.json"
    @bills = Bill.new(JSON.load(open(source)))
    #@bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:total)
    end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:called, :duration, :cost, :callCharges_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/call_charges_helper.rb
module CallChargesHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/read_data_helper.rb
module ReadDataHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/sky_stores_helper.rb
module SkyStoresHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bills</h1>

<table>
  <thead>
    <tr>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.total %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @bill.total %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :called %><br>
    <%= f.text_field :called %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :callCharges_id %><br>
    <%= f.number_field :callCharges_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calls</h1>

<table>
  <thead>
    <tr>
      <th>Called</th>
      <th>Duration</th>
      <th>Cost</th>
      <th>Callcharges</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calls.each do |call| %>
      <tr>
        <td><%= call.called %></td>
        <td><%= call.duration %></td>
        <td><%= call.cost %></td>
        <td><%= call.callCharges_id %></td>
        <td><%= link_to 'Show', call %></td>
        <td><%= link_to 'Edit', edit_call_path(call) %></td>
        <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New Call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Called:</strong>
  <%= @call.called %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @call.duration %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @call.cost %>
</p>

<p>
  <strong>Callcharges:</strong>
  <%= @call.callCharges_id %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>