config/routes.rb
Rails.application.routes.draw do
  resources :read_data
  resources :periods
  resources :buy_and_keeps
  resources :rentals
  resources :sky_stores
  resources :calls
  resources :call_charges
  resources :subscriptions
  resources :packages
  resources :statements
  resources :bills

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/models/buy_and_keep.rb
class BuyAndKeep < ActiveRecord::Base
end

app/models/call.rb
class Call < ActiveRecord::Base
end

app/models/call_charge.rb
class CallCharge < ActiveRecord::Base
end

app/models/package.rb
class Package < ActiveRecord::Base
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/read_datum.rb
class ReadDatum < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/models/sky_store.rb
class SkyStore < ActiveRecord::Base
end

app/models/statement.rb
class Statement < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  require 'json'
  require 'open-uri'

  # GET /bills
  # GET /bills.json
  def index
    source = "http://safe-plains-5453.herokuapp.com/bill.json"
    @bills = Bill.new(JSON.load(open(source)))
    #@bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:total)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:title, :cost, :skyStore_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/call_charges_helper.rb
module CallChargesHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/read_data_helper.rb
module ReadDataHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/sky_stores_helper.rb
module SkyStoresHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/rentals/_form.html.erb
<%= form_for(@rental) do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :skyStore_id %><br>
    <%= f.number_field :skyStore_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cost</th>
      <th>Skystore</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.title %></td>
        <td><%= rental.cost %></td>
        <td><%= rental.skyStore_id %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form' %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @rental.title %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @rental.cost %>
</p>

<p>
  <strong>Skystore:</strong>
  <%= @rental.skyStore_id %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>